language: cpp
dist: bionic
cache: ccache

services:
  - docker

branches:
  only:
    - master
    - /^\d+(\.\d+)*/

env:
  global:
    - PYTHON_EXECUTABLE="/usr/bin/python3"

jobs:
  include:
    - stage: "Code formatting"
      name: "Clang-format"
      if: NOT type = cron
      script: docker run --rm --tty -v "$PWD:/scipp" scipp/ci bash -c "cd /scipp && .travis/check_clang_format.sh"

    - stage: "Code formatting"
      name: "Flake8"
      if: NOT type = cron
      script: docker run --rm --tty -v "$PWD:/scipp" scipp/ci bash -c "cd /scipp && .travis/check_flake8.sh"

    - stage: "Unit tests"
      name: "gcc"
      if: NOT type = cron
      script: docker run --rm --tty -e CC=gcc-8 -e CXX=g++-8 -e PYTHON_EXECUTABLE=/opt/conda/bin/python -v "$PWD:/scipp" scipp/ci bash -c "cd /scipp && .travis/run_tests.sh"

    - stage: "Unit tests"
      name: "clang"
      if: NOT type = cron
      script: docker run --rm --tty -e CC=clang-7 -e CXX=clang++-7 -e PYTHON_EXECUTABLE=/opt/conda/bin/python -v "$PWD:/scipp" scipp/ci bash -c "cd /scipp && .travis/run_tests.sh"

    - stage: "Unit tests"
      os: osx
      name: "apple clang"
      if: NOT type = cron
      osx_image: xcode10.2
      before_install: brew install ccache ninja
      env:
        - PYTHON_EXECUTABLE="/usr/local/bin/python3"
      script: .travis/run_tests.sh -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF

    - stage: "Deploy"
      name: "conda linux"
      if: NOT type = cron AND branch = master AND NOT type = pull_request
      git:
        depth: false
      env:
        - PATH="$HOME/miniconda/bin:$PATH"
      install: .travis/install_conda.sh "Miniconda3-latest-Linux-x86_64.sh"
      script:
        - .travis/conda_build_and_deploy.sh --label 'dev'
        - .travis/trigger_docker_build.sh
        - .travis/trigger_readthedocs_build.sh

    - stage: "Deploy"
      os: osx
      osx_image: xcode10.2
      name: "conda osx"
      if: NOT type = cron AND branch = master AND NOT type = pull_request
      git:
        depth: false
      env:
        - PATH="$HOME/miniconda/bin:$PATH"
        - CC=/usr/bin/clang
        - CXX=/usr/bin/clang++
        - OSX_VERSION=10.14
      install:
        - .travis/install_conda.sh "Miniconda3-latest-MacOSX-x86_64.sh"
      script: travis_wait .travis/conda_build_and_deploy.sh --label 'dev'

    - stage: "Deploy"
      name: "conda linux python3.6"
      if: type = cron AND branch = master
      git:
        depth: false
      env:
        - PATH="$HOME/miniconda/bin:$PATH"
      install: .travis/install_conda.sh "Miniconda3-latest-Linux-x86_64.sh"
      script:
        - travis_wait .travis/conda_build_and_deploy.sh --label 'dev' --python 3.6

    - stage: "Deploy"
      name: "release conda linux"
      if: NOT type = cron AND NOT type = pull_request AND tag =~ /^\d+(\.\d+)*/
      git:
        depth: false
      env:
        - PATH="$HOME/miniconda/bin:$PATH"
      install: .travis/install_conda.sh "Miniconda3-latest-Linux-x86_64.sh"
      script:
        - travis_wait .travis/conda_build_and_deploy.sh
        - travis_wait .travis/conda_build_and_deploy.sh --python 3.6

    - stage: "Deploy"
      os: osx
      osx_image: xcode10.2
      name: "release conda osx"
      if: NOT type = cron AND NOT type = pull_request AND tag =~ /^\d+(\.\d+)*/
      git:
        depth: false
      env:
        - PATH="$HOME/miniconda/bin:$PATH"
        - CC=/usr/bin/clang
        - CXX=/usr/bin/clang++
        - OSX_VERSION=10.14
      install:
        - .travis/install_conda.sh "Miniconda3-latest-MacOSX-x86_64.sh"
      script: travis_wait .travis/conda_build_and_deploy.sh
