version: '{build}'
os: Visual Studio 2019

matrix:
  fast_finish: true

platform:
  - x64

configuration:
  - Release

environment:
  PYTHON_VERSION: 3.6
  MINICONDA: C:\Miniconda36-x64

install:
- cd %APPVEYOR_BUILD_FOLDER%
- git submodule update --init
- mkdir build
- cd build
- set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"

build_script:
- cmake -G "Visual Studio 16 2019" -A x64 -DPYTHON_EXECUTABLE="C:/Python36-x64/python.exe" -DCMAKE_INSTALL_PREFIX=../install ..
# - cmake --build . --config %CONFIGURATION% --target install all-tests

test_script:
# - '%APPVEYOR_BUILD_FOLDER%\build\common\test\%CONFIGURATION%\scipp-common-test.exe'
# - '%APPVEYOR_BUILD_FOLDER%\build\core\test\%CONFIGURATION%\scipp-core-test.exe'
# - '%APPVEYOR_BUILD_FOLDER%\build\neutron\test\%CONFIGURATION%\scipp-neutron-test.exe'
# - '%APPVEYOR_BUILD_FOLDER%\build\units\test\%CONFIGURATION%\scipp-units-test.exe'
# - C:\Python36-x64\python.exe -m pip install -r ..\python\requirements.txt
# - set PYTHONPATH=%PYTHONPATH%;..\install
# - C:\Python36-x64\python.exe -m pytest ..\python

deploy_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - rd build /s/q
  - mkdir build
  - cd build
  - conda config --set always_yes yes --set changeps1 no
  - conda install -c conda-forge conda-build anaconda-client
  - conda update libarchive
  - if "%APPVEYOR_REPO_TAG%"=="true" set LABEL=main
  - if "%APPVEYOR_REPO_TAG%"=="false" if "%APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH%"=="master" set LABEL=dev
  - echo using label %LABEL%
  - conda-build --user scipp --token %ANACONDA_TOKEN% --label %LABEL% ../conda
