parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

trigger:
  - next-ci # TODO change

pr: none

extends:
  template: templates/stages.yml
  parameters:
    verbose: ${{ parameters.verbose }}
    py_versions:
      linux: ['3.7']
      osx: ['3.7']
      windows: ['3.7']
    deploy: true
    conda_label: 'next'
    publish_docs: false
